// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vladopadikk/order-delivery-app/auth-service/internal/models"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, loginIn models.LoginInput) (models.TokenResponse, error) {
	ret := _mock.Called(ctx, loginIn)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 models.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LoginInput) (models.TokenResponse, error)); ok {
		return returnFunc(ctx, loginIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LoginInput) models.TokenResponse); ok {
		r0 = returnFunc(ctx, loginIn)
	} else {
		r0 = ret.Get(0).(models.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.LoginInput) error); ok {
		r1 = returnFunc(ctx, loginIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - loginIn models.LoginInput
func (_e *MockAuthService_Expecter) Login(ctx any, loginIn any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, loginIn)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, loginIn models.LoginInput)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.LoginInput
		if args[1] != nil {
			arg1 = args[1].(models.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(tokenResponse models.TokenResponse, err error) *MockAuthService_Login_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, loginIn models.LoginInput) (models.TokenResponse, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, input models.UserInput) (models.UserResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserInput) (models.UserResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserInput) models.UserResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(models.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UserInput
func (_e *MockAuthService_Expecter) Register(ctx any, input any) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, input)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, input models.UserInput)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UserInput
		if args[1] != nil {
			arg1 = args[1].(models.UserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(userResponse models.UserResponse, err error) *MockAuthService_Register_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, input models.UserInput) (models.UserResponse, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
