// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vladopadikk/order-delivery-app/orders-service/internal/database"
	"github.com/vladopadikk/order-delivery-app/orders-service/internal/models"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) BeginTx(ctx context.Context) (database.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 database.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (database.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) database.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockOrderRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderRepository_Expecter) BeginTx(ctx any) *MockOrderRepository_BeginTx_Call {
	return &MockOrderRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockOrderRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockOrderRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderRepository_BeginTx_Call) Return(tx database.Tx, err error) *MockOrderRepository_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockOrderRepository_BeginTx_Call) RunAndReturn(run func(ctx context.Context) (database.Tx, error)) *MockOrderRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, exec database.Executor, userID int64, status string, totalPrice float64, deliveryAddress string) (models.Order, error) {
	ret := _mock.Called(ctx, exec, userID, status, totalPrice, deliveryAddress)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Executor, int64, string, float64, string) (models.Order, error)); ok {
		return returnFunc(ctx, exec, userID, status, totalPrice, deliveryAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Executor, int64, string, float64, string) models.Order); ok {
		r0 = returnFunc(ctx, exec, userID, status, totalPrice, deliveryAddress)
	} else {
		r0 = ret.Get(0).(models.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.Executor, int64, string, float64, string) error); ok {
		r1 = returnFunc(ctx, exec, userID, status, totalPrice, deliveryAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - exec database.Executor
//   - userID int64
//   - status string
//   - totalPrice float64
//   - deliveryAddress string
func (_e *MockOrderRepository_Expecter) Create(ctx any, exec any, userID any, status any, totalPrice any, deliveryAddress any) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, exec, userID, status, totalPrice, deliveryAddress)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, exec database.Executor, userID int64, status string, totalPrice float64, deliveryAddress string)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.Executor
		if args[1] != nil {
			arg1 = args[1].(database.Executor)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(order models.Order, err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, exec database.Executor, userID int64, status string, totalPrice float64, deliveryAddress string) (models.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItems provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) CreateItems(ctx context.Context, exec database.Executor, order_id int64, orderItem models.OrderItemInput) error {
	ret := _mock.Called(ctx, exec, order_id, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for CreateItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Executor, int64, models.OrderItemInput) error); ok {
		r0 = returnFunc(ctx, exec, order_id, orderItem)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_CreateItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItems'
type MockOrderRepository_CreateItems_Call struct {
	*mock.Call
}

// CreateItems is a helper method to define mock.On call
//   - ctx context.Context
//   - exec database.Executor
//   - order_id int64
//   - orderItem models.OrderItemInput
func (_e *MockOrderRepository_Expecter) CreateItems(ctx any, exec any, order_id any, orderItem any) *MockOrderRepository_CreateItems_Call {
	return &MockOrderRepository_CreateItems_Call{Call: _e.mock.On("CreateItems", ctx, exec, order_id, orderItem)}
}

func (_c *MockOrderRepository_CreateItems_Call) Run(run func(ctx context.Context, exec database.Executor, order_id int64, orderItem models.OrderItemInput)) *MockOrderRepository_CreateItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.Executor
		if args[1] != nil {
			arg1 = args[1].(database.Executor)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 models.OrderItemInput
		if args[3] != nil {
			arg3 = args[3].(models.OrderItemInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_CreateItems_Call) Return(err error) *MockOrderRepository_CreateItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_CreateItems_Call) RunAndReturn(run func(ctx context.Context, exec database.Executor, order_id int64, orderItem models.OrderItemInput) error) *MockOrderRepository_CreateItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetOrders(ctx context.Context, userID int64) ([]models.OrderResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []models.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.OrderResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.OrderResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderRepository_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockOrderRepository_Expecter) GetOrders(ctx any, userID any) *MockOrderRepository_GetOrders_Call {
	return &MockOrderRepository_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, userID)}
}

func (_c *MockOrderRepository_GetOrders_Call) Run(run func(ctx context.Context, userID int64)) *MockOrderRepository_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetOrders_Call) Return(orderResponses []models.OrderResponse, err error) *MockOrderRepository_GetOrders_Call {
	_c.Call.Return(orderResponses, err)
	return _c
}

func (_c *MockOrderRepository_GetOrders_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.OrderResponse, error)) *MockOrderRepository_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateStatus(ctx context.Context, orderID int64, status string) error {
	ret := _mock.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int64
//   - status string
func (_e *MockOrderRepository_Expecter) UpdateStatus(ctx any, orderID any, status any) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderID, status)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, orderID int64, status string)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(err error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, orderID int64, status string) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
