// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vladopadikk/order-delivery-app/orders-service/internal/models"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// PublishOrderCreated provides a mock function for the type MockProducer
func (_mock *MockProducer) PublishOrderCreated(ctx context.Context, event models.OrderCreatedEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrderCreatedEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_PublishOrderCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderCreated'
type MockProducer_PublishOrderCreated_Call struct {
	*mock.Call
}

// PublishOrderCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - event models.OrderCreatedEvent
func (_e *MockProducer_Expecter) PublishOrderCreated(ctx any, event any) *MockProducer_PublishOrderCreated_Call {
	return &MockProducer_PublishOrderCreated_Call{Call: _e.mock.On("PublishOrderCreated", ctx, event)}
}

func (_c *MockProducer_PublishOrderCreated_Call) Run(run func(ctx context.Context, event models.OrderCreatedEvent)) *MockProducer_PublishOrderCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.OrderCreatedEvent
		if args[1] != nil {
			arg1 = args[1].(models.OrderCreatedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_PublishOrderCreated_Call) Return(err error) *MockProducer_PublishOrderCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_PublishOrderCreated_Call) RunAndReturn(run func(ctx context.Context, event models.OrderCreatedEvent) error) *MockProducer_PublishOrderCreated_Call {
	_c.Call.Return(run)
	return _c
}
