// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vladopadikk/order-delivery-app/orders-service/internal/models"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CreateOrder(ctx context.Context, userID int64, orderIn models.OrderInput) (models.OrderResponse, error) {
	ret := _mock.Called(ctx, userID, orderIn)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 models.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.OrderInput) (models.OrderResponse, error)); ok {
		return returnFunc(ctx, userID, orderIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.OrderInput) models.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, orderIn)
	} else {
		r0 = ret.Get(0).(models.OrderResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, models.OrderInput) error); ok {
		r1 = returnFunc(ctx, userID, orderIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderIn models.OrderInput
func (_e *MockOrderService_Expecter) CreateOrder(ctx any, userID any, orderIn any) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, orderIn)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, userID int64, orderIn models.OrderInput)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.OrderInput
		if args[2] != nil {
			arg2 = args[2].(models.OrderInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(orderResponse models.OrderResponse, err error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID int64, orderIn models.OrderInput) (models.OrderResponse, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderList provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrderList(ctx context.Context, userID int64) (models.OrderListResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderList")
	}

	var r0 models.OrderListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.OrderListResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.OrderListResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.OrderListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrderList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderList'
type MockOrderService_GetOrderList_Call struct {
	*mock.Call
}

// GetOrderList is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockOrderService_Expecter) GetOrderList(ctx any, userID any) *MockOrderService_GetOrderList_Call {
	return &MockOrderService_GetOrderList_Call{Call: _e.mock.On("GetOrderList", ctx, userID)}
}

func (_c *MockOrderService_GetOrderList_Call) Run(run func(ctx context.Context, userID int64)) *MockOrderService_GetOrderList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrderList_Call) Return(orderListResponse models.OrderListResponse, err error) *MockOrderService_GetOrderList_Call {
	_c.Call.Return(orderListResponse, err)
	return _c
}

func (_c *MockOrderService_GetOrderList_Call) RunAndReturn(run func(ctx context.Context, userID int64) (models.OrderListResponse, error)) *MockOrderService_GetOrderList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockOrderService
func (_mock *MockOrderService) UpdateOrderStatus(ctx context.Context, orderID int64, status string) error {
	ret := _mock.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderService_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int64
//   - status string
func (_e *MockOrderService_Expecter) UpdateOrderStatus(ctx any, orderID any, status any) *MockOrderService_UpdateOrderStatus_Call {
	return &MockOrderService_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderID, status)}
}

func (_c *MockOrderService_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderID int64, status string)) *MockOrderService_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_UpdateOrderStatus_Call) Return(err error) *MockOrderService_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, orderID int64, status string) error) *MockOrderService_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}
